add VostfreeProvider
recloudstream/cloudstream-extensions-multilingual pull request #16
Opened 2022-09-04 09:17 UTC by Eddy976

Add vostfree.cx provider

2022-09-04 11:52 UTC, LagradOst requested changes
please autoformat your code

2022-09-04 11:52 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/MytvExtractor.kt
> +        with(html) {  // raised error ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED (3003) is due to the response: "error_nofile"
why with????

2022-09-04 11:52 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +        isSaison.forEach {
do apmap as you do a get request

2022-09-04 11:52 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +            title =title.replace("Season","").replace("season","").replace("SEASON","")
you are doing the same thing twice here, remove a line

2022-09-04 11:52 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +                    "VIP"  -> playerUrl = codePlayload
do you can playerUrl = when(playerName) check out https://kotlinlang.org/docs/control-flow.html#when-expression
you can also match several with the same 
"VIP", "Upvid", .... -> codePlayload

2022-09-04 11:52 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +        animeDubStatus.add("/animes-vf/")
declare this as mainpage for infinate loading

2022-09-04 15:20 UTC, Eddy976 commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +        isSaison.forEach {
with apmap i don't get the result i excpet

2022-09-04 15:26 UTC, Eddy976 commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +                    "VIP"  -> playerUrl = codePlayload
Thanks ! it's work

2022-09-04 17:28 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +        isSaison.forEach {
apmap works the same as map but with parallel execution, understand map first

2022-09-05 18:01 UTC, Eddy976 commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +        isSaison.forEach {
i used mapnotnull instead

2022-09-05 18:03 UTC, Eddy976 commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +        animeDubStatus.add("/animes-vf/")
i optimized the mainpage

2022-09-06 22:41 UTC, LagradOst reviewed
👍

2022-09-06 22:41 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +        document.select(" select.new_player_selector > option").mapNotNull {
good effort, however you are using map incorrectly here. map is meant to return a result. `val squares = listOf(1,2,3,4).map { num -> num*num }` this is a example of squaring numbers, however in your case you want to return a list of episodes. If you really want to use episodes.add instead then use a forEach

2022-09-06 22:41 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +        isSaison.mapNotNull {
you are doing a get request so use apmap (async parallel map) because it can do all get requests in parallel

2022-09-12 18:42 UTC, LagradOst reviewed
Dont add any more sites to this pr, it just becomes too much for any sort of sane review. if you want to add more sites while this is in progress, open up another pull requests.

1. autoformat your code
2. start variablenames with a lowercase letter
3. learn the difference between map, apmap and foreach
4. take a look at listOf() and "a" to "b" instead of Pair("a","b")
5. learn about when [case](https://kotlinlang.org/docs/control-flow.html#when-expression)

2022-09-12 18:42 UTC, LagradOst commented on WiflixProvider/src/main/kotlin/com/lagradost/WiflixProvider.kt
> +            var playerUrl = "https" + player.attr("href").replace("(.*)https".toRegex(), "")
fixurl

2022-09-12 18:42 UTC, LagradOst commented on WiflixProvider/src/main/kotlin/com/lagradost/WiflixProvider.kt
> +            cssCodeForPlayer = "div.ep$numeroEpisode" + "vf > a"
why do you add here?

2022-09-12 18:42 UTC, LagradOst commented on WiflixProvider/src/main/kotlin/com/lagradost/WiflixProvider.kt
> +        val numeroEpisode = if (parsedInfo?.episodeNumber != null) {
what is this???? just do numeroEpisode = parsedInfo.episodeNumber

2022-09-12 18:42 UTC, LagradOst commented on WiflixProvider/src/main/kotlin/com/lagradost/WiflixProvider.kt
> +        val url = if (parsedInfo?.url != null) {
url = parsedInfo?.url ?: data

2022-09-12 18:42 UTC, LagradOst commented on WiflixProvider/src/main/kotlin/com/lagradost/WiflixProvider.kt
> +    private fun Elements.takeEpisode(url: String, DuborSub:String?): ArrayList<Episode> {
start variables with a lowercase letter

2022-09-12 18:42 UTC, LagradOst commented on WiflixProvider/src/main/kotlin/com/lagradost/WiflixProvider.kt
> +            results.apmap { article ->  // avec mapnotnull si un élément est null, il sera automatiquement enlevé de la liste
you dont do any get request, so do map

2022-09-12 18:42 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +            movies.apmap { article ->  // avec mapnotnull si un élément est null, il sera automatiquement enlevé de la liste
map

2022-09-12 18:42 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +        val posterUrl = mainUrl + poster.select("> img").attr("src")
fixurl

2022-09-12 18:42 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +                        else -> ""
return @apmap

2022-09-12 18:42 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +        val url = if (parsedInfo?.url != null) {
parsedInfo?.url ?: data

2022-09-12 18:42 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +        urlSaison.forEach {
apmap because you use app.get

2022-09-12 18:42 UTC, LagradOst commented on NekosamaProvider/src/main/kotlin/com/lagradost/NekosamaProvider.kt
> +            movies.apmap { article ->  // avec mapnotnull si un élément est null, il sera automatiquement enlevé de la liste
map

2022-09-12 18:42 UTC, LagradOst commented on NekosamaProvider/src/main/kotlin/com/lagradost/NekosamaProvider.kt
> +        results.forEach { InfoEpisode ->
start with lowercase

2022-09-12 18:42 UTC, LagradOst commented on NekosamaProvider/src/main/kotlin/com/lagradost/NekosamaProvider.kt
> +            if (playerUrl != "")
!playerUrl.isNullOrBlank()

2022-09-12 18:42 UTC, LagradOst commented on NekosamaProvider/src/main/kotlin/com/lagradost/NekosamaProvider.kt
> +            val EpisodeNum = srcScriptEpisode.find(episodeScript)?.groupValues?.get(1)?.toInt()
lowercase

2022-09-12 18:42 UTC, LagradOst commented on NekosamaProvider/src/main/kotlin/com/lagradost/NekosamaProvider.kt
> +            links.apmap {
just do `return listOf("$mainUrl/animes-search-vf.json" to "(VF) ", "$mainUrl/animes-search-vostfr.json" to "(Vostfr) ").apmap { url, name ->`

2022-09-12 18:42 UTC, LagradOst commented on NekosamaProvider/src/main/kotlin/com/lagradost/NekosamaProvider.kt
> +            var title = this.title
`listOf(title,title_french,title_english,title_romanji).filternotnull()`

2022-09-12 18:42 UTC, LagradOst commented on MesFilmsProvider/src/main/kotlin/com/lagradost/MesFilmsProvider.kt
> +        val html = app.get("$mainUrl/tendance/?get=movies").text
val document = app.get("$mainUrl/tendance/?get=movies").document

2022-09-12 18:42 UTC, LagradOst commented on MesFilmsProvider/src/main/kotlin/com/lagradost/MesFilmsProvider.kt
> +        val html = app.get(url).text // récupere le texte sur la page (requète http)
.document

2022-09-12 18:42 UTC, LagradOst commented on MesFilmsProvider/src/main/kotlin/com/lagradost/MesFilmsProvider.kt
> +        val html = app.get(link).text // app.get() permet de télécharger la page html avec une requete HTTP (get)
.document

2022-09-12 18:42 UTC, LagradOst commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +        if (qualityExtracted.contains("HDLight")) {
fr dont do this, use when or add more to getQualityFromString

2022-09-12 18:42 UTC, LagradOst commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +                this.year = year?.toInt()
toIntOrNull

2022-09-15 23:43 UTC, Eddy976 commented on build.gradle.kts
> +        implementation ("me.xdrop:fuzzywuzzy:1.4.0")
yes ! the search function in Nekosamaprovider need it

2022-09-19 08:25 UTC, LagradOst commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +    private val interceptor = CloudflareKiller()
where is this used???

2022-09-19 08:25 UTC, LagradOst commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +                    println(header)
remove all println

2022-09-19 08:25 UTC, LagradOst commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +            qualityExtracted.contains("HDLight") -> getQualityFromString("HD")
good use of when, however you can replace getQualityFromString("HD") here with the actual enum value

2022-09-19 08:25 UTC, LagradOst commented on NekosamaProvider/src/main/kotlin/com/lagradost/NekosamaProvider.kt
> +            val version = it.second
instead of this, write
.apmap { (url, version) ->

2022-09-19 08:25 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +            fixUrl("/index.php?do=search&subaction=search&story=$query&submit=Submit+Query") // L'url pour chercher un anime de dragon sera donc: 'https://vostfree.cx/index.php?story=dragon&do=search
there is no need to do fixUrl as you can simply prefix with "$mainUrl

2022-09-19 08:25 UTC, LagradOst commented on VostfreeProvider/src/main/kotlin/com/lagradost/VostfreeProvider.kt
> +        urlSaison.apmap {it ->
.apmap { urlseason->

2022-09-19 08:25 UTC, LagradOst commented on WiflixProvider/src/main/kotlin/com/lagradost/WiflixProvider.kt
> +            "div.ep$numeroEpisode" + "vf > a"
"div.ep${numeroEpisode}vf > a"

2022-09-23 18:10 UTC, LagradOst commented
Ok, this is too much for me to review. So if you feel like your code is **clean** and ready for merge then I will merge it into main.

2022-09-24 09:32 UTC, Eddy976 commented
You can merge it.

2022-09-24 10:27 UTC, C10udburst requested changes

2022-09-24 10:27 UTC, C10udburst commented on FrenchStreamProvider/build.gradle.kts
> +     authors = listOf("Sarlay feat Eddy")
this is a list, you can do `listOf("Sarlay", "Eddy")`

2022-09-25 10:23 UTC, Eddy976 commented on FrenchStreamProvider/build.gradle.kts
> +     authors = listOf("Sarlay feat Eddy")
Thanks ! I did it

2022-09-25 10:43 UTC, C10udburst approved these changes

2022-09-26 15:20 UTC, merged