Added MaciptvProvider.
recloudstream/cloudstream-extensions-multilingual pull request #38
Opened 2022-10-22 22:30 UTC by Eddy976

Added MaciptvProvider which allows to use iptv accounts (url + mac address). It may be necessary to add all the other languages

2022-10-22 22:46 UTC, C10udburst requested changes

2022-10-22 22:46 UTC, C10udburst commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIptvSettingsFragment.kt
> +
`maciptvAPI.createAccountUrl` is empty so you probably didnt intend for this to be here

Maybe remove infoView and its connected layout from the xml

2022-10-22 22:46 UTC, C10udburst commented on MaciptvProvider/src/main/res/drawable/nginx.xml
> +</vector>
this looks like the nginx icon file are you sure thats what you want?

2022-10-22 22:46 UTC, C10udburst commented on MaciptvProvider/src/main/res/values-pl/strings.xml
> +</resources>
please remove all the untranslated files you've copied from nginx so its not confusing for people not using english or french

2022-10-22 22:49 UTC, C10udburst commented
[CodeFactor](https://www.codefactor.io/repository/github/recloudstream/cloudstream-extensions-multilingual) found multiple issues last seen at c18ecfc3c3cbe559afd2fb2451d2f6b6a245c08c:

#### Parentheses in (getLang == &quot;AR&quot;) are unnecessary and can be replaced with: getLang == &quot;AR&quot;
- [ ]  [MaciptvProvider\src\main\kotlin\com\lagradost\MacIPTVProvider.kt:545](https://github.com/recloudstream/cloudstream-extensions-multilingual/blob/c18ecfc3c3cbe559afd2fb2451d2f6b6a245c08c/MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt#L545)

#### Parentheses in (categoryTitle.uppercase()                         .contains(rgxcodeCountry) || categoryTitle.isContainsTargetCountry()) are unnecessary and can be replaced with: categoryTitle.uppercase()                         .contains(rgxcodeCountry) || categoryTitle.isContainsTargetCountry()
- [ ]  [MaciptvProvider\src\main\kotlin\com\lagradost\MacIPTVProvider.kt:707](https://github.com/recloudstream/cloudstream-extensions-multilingual/blob/c18ecfc3c3cbe559afd2fb2451d2f6b6a245c08c/MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt#L707)

#### Parentheses in (getLang == &quot;FR&quot;) are unnecessary and can be replaced with: getLang == &quot;FR&quot;
- [ ]  [MaciptvProvider\src\main\kotlin\com\lagradost\MacIPTVProvider.kt:531](https://github.com/recloudstream/cloudstream-extensions-multilingual/blob/c18ecfc3c3cbe559afd2fb2451d2f6b6a245c08c/MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt#L531)

#### Parentheses in (upperSTR == &quot;EN&quot;) are unnecessary and can be replaced with: upperSTR == &quot;EN&quot;
- [ ]  [MaciptvProvider\src\main\kotlin\com\lagradost\MacIPTVProvider.kt:519](https://github.com/recloudstream/cloudstream-extensions-multilingual/blob/c18ecfc3c3cbe559afd2fb2451d2f6b6a245c08c/MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt#L519)

#### Parentheses in (getLang == &quot;EN&quot;) are unnecessary and can be replaced with: getLang == &quot;EN&quot;
- [ ]  [MaciptvProvider\src\main\kotlin\com\lagradost\MacIPTVProvider.kt:538](https://github.com/recloudstream/cloudstream-extensions-multilingual/blob/c18ecfc3c3cbe559afd2fb2451d2f6b6a245c08c/MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt#L538)

#### Parentheses in (media.tv_genre_id == idGenre) are unnecessary and can be replaced with: media.tv_genre_id == idGenre
- [ ]  [MaciptvProvider\src\main\kotlin\com\lagradost\MacIPTVProvider.kt:684](https://github.com/recloudstream/cloudstream-extensions-multilingual/blob/c18ecfc3c3cbe559afd2fb2451d2f6b6a245c08c/MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt#L684)
- [ ]  [MaciptvProvider\src\main\kotlin\com\lagradost\MacIPTVProvider.kt:690](https://github.com/recloudstream/cloudstream-extensions-multilingual/blob/c18ecfc3c3cbe559afd2fb2451d2f6b6a245c08c/MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt#L690)

2022-10-22 23:19 UTC, Eddy976 commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIptvSettingsFragment.kt
> +
Honestly I didn't really understand how you did it for ngix. I just wanted to be able to create accounts and I copied and pasted what I thought was necessary;

2022-10-23 07:38 UTC, Eddy976 commented on MaciptvProvider/src/main/res/drawable/nginx.xml
> +</vector>
Honestly I didn't really understand how it work for ngix. I just wanted to be able to create accounts and I copied and pasted what I thought was necessary;

2022-10-23 07:46 UTC, Eddy976 commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIptvSettingsFragment.kt
> +
I took these files from the ngix extension.  In my android studio project, I was not able to solve the dependency issues(for example: BuildConfig.LIBRARY_PACKAGE_NAME). Therefore it is difficult for me to debug this code to try to understand how it works.

2022-10-23 08:08 UTC, C10udburst commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIptvSettingsFragment.kt
> +
Yeah sorry, we don't have any documentation about creating UIs yet. 

`BuildConfig.LIBRARY_PACKAGE_NAME` can be undefined in android studio, but after you build your extension once the issue should be solved

2022-10-23 10:23 UTC, Eddy976 commented
I did not understand the 3 errors from CodeFactor

2022-10-23 10:40 UTC, C10udburst commented
> I did not understand the 3 errors from CodeFactor

It's fine, they just mean that these methods contain a lot of code.

2022-10-25 18:14 UTC, Eddy976 commented
I tried to optimize the code. I just started with Kotlin, so there are a lot of things I don't know. So I might have complicated my life :)

2022-11-07 11:18 UTC, Blatzar reviewed
Very hard to understand whats going on in the provider :pensive: 
Many global variables to keep track of and few comments

2022-11-07 11:18 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +        arraymediaPlaylist.sortByname(query).take(resultsSearchNbr).forEach { media ->
Using map is better than adding to list, like this:

` val searchResutls = arraymediaPlaylist.sortByname(query).take(resultsSearchNbr).map { media -> ....`

See https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map.html

2022-11-07 11:18 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +        val media = url.replace(mainUrl, "").getDataChannelFromString()
Instead of doing it like this use json serialization
when passing in the data as the url do: media.toJson()

when getting the data do: parseJson<Channel>(url)
That will make the code cleaner and more future proof

2022-11-07 11:18 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +            when (true) {
use when `(getLang) {`
then you can do 
`"FR" -> {`

2022-11-07 11:18 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +            when (true) {
In fact you have the same code everywhere so you can just make a hashmap

`val langs = hashmapOf("FR" to arrayListOf("french", "france")......)`

then just do something like
`return langs[getLang]?.any { this.contains(findKeyWord(it), ignoreCase = true) } ?: false`

2022-11-07 11:18 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +            flag = when (true) {
`return when {`

2022-11-08 09:31 UTC, Eddy976 reviewed
changes done

2022-11-15 12:54 UTC, Blatzar reviewed
More global variables makes for hard to debug code, please try to cut down where possible 🙏

2022-11-15 12:54 UTC, Blatzar commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +    init {
I'm not too keen on you running much on init :(
With 200 extensions then it's 200 requests as you open the app, please move this to when it's needed, like homepage and search and then make sure it runs once.

2022-11-15 12:54 UTC, Blatzar commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +                        AppUtils.tryParseJson<ArrayList<mediaData>>(app.get("https://raw.githubusercontent.com/Eddy976/cloudstream-extensions-eddy/ressources/fetchwebsite.json").text)!!
TryParseJson is useless if you put
!!
Use parseJson to get more intelligible exceptions when the parsing fails

2022-11-15 12:54 UTC, Blatzar commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +                        if (it.title.lowercase().contains("french-stream")) {
You can use contains(ignoreCase = true)

2022-11-15 12:54 UTC, Blatzar commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +                    AppUtils.tryParseJson<ArrayList<mediaData>>(app.get("https://raw.githubusercontent.com/Eddy976/cloudstream-extensions-eddy/ressources/fetchwebsite.json").text)!!
This effectively crashes the extension if this request fails for some reason, don't use !!

2022-11-15 12:54 UTC, Blatzar commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +                    data.forEach {
Using FirstOrNull allows quicker loop exit and nets more readable code

2022-11-15 12:54 UTC, Blatzar commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +        }.toMutableList()
Why is this mutable?

2022-11-15 12:54 UTC, Blatzar commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +                val isvostfr = data.takeLast(8) == "*vostfr*"
Why not use endsWith()?

2022-11-15 12:54 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +
Please move global variables to the top

2022-11-15 12:54 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +    private var codeCountry = lang
More spread out global variables

2022-11-15 12:54 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +            return langs[getLang]?.any { this.uppercase().contains(findKeyWord(it)) } ?: false
Nice!

2022-11-15 12:54 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +            return mutableListOf(
Why mutable list?

2022-11-15 12:54 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +            arraychannel.add(
You can just do
val arrayChannel = listOf(....
To inline the channels

2022-11-15 12:54 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +                    "${provider.mainUrl}I_Need_Help",
What do you need help with?

2022-11-15 12:54 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +            val sequence = when (true) {
when(upperSTR)

2022-11-15 12:54 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +            while (itr.hasNext()) {
Why iterators and not at least for loops?
It makes for confusing code :(

2022-11-15 12:54 UTC, Blatzar commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIptvAPI.kt
> +        if (data.server.isNullOrBlank() || !data.password?.contains("""(([0-9A-Za-z]{2}[:-]){5}[0-9A-Za-z]{2})""".toRegex())!!) return false // we require a server
What's this password regex?

2022-11-15 12:54 UTC, Blatzar commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +                    AppUtils.tryParseJson<ArrayList<mediaData>>(app.get("https://raw.githubusercontent.com/Eddy976/cloudstream-extensions-eddy/ressources/fetchwebsite.json").text)!!
This also effectively removes the ability to clone the site, perhaps check if the url is changed 🤔

2022-11-15 12:55 UTC, Blatzar commented
Not all comments require a change, but worth considering

2022-11-15 14:22 UTC, Eddy976 commented on FrenchStreamProvider/src/main/kotlin/com/lagradost/FrenchStreamProvider.kt
> +    init {
OK i will do that later. But for the momment I think it's better to disable french stream  because the site has become unstable (changing url all the time, seems to add a cloudflare). We have to see what will happen. So i will let the old version

2022-11-15 14:28 UTC, Eddy976 commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +            while (itr.hasNext()) {
i need to remove element from the list

2022-11-15 15:01 UTC, Eddy976 commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIPTVProvider.kt
> +                    "${provider.mainUrl}I_Need_Help",
It just a code for the load function to detect when we click on it. Since I don't select all the content because it is too big, I want to at least display the countries and categories available. So the user will know what is available and can select his own country or categories via the account creation tag

2022-11-15 20:12 UTC, Eddy976 commented
No need a review for french-stream. I have put back the old cod because for the momment I think it's better to disable french stream because the site has become unstable (changing url all the time, seems to add a cloudflare). We have to see what will happen. So i will let the old version

2022-11-15 20:13 UTC, Eddy976 commented on MaciptvProvider/src/main/kotlin/com/lagradost/MacIptvAPI.kt
> +        if (data.server.isNullOrBlank() || !data.password?.contains("""(([0-9A-Za-z]{2}[:-]){5}[0-9A-Za-z]{2})""".toRegex())!!) return false // we require a server
a mac address

2022-11-28 16:26 UTC, closed without merging