quality shit and removing domains name from source
recloudstream/cloudstream-extensions-multilingual pull request #58
Opened 2022-11-28 14:58 UTC by ImZaw

2022-11-28 15:08 UTC, ImZaw commented
wait dont push

2022-11-28 15:19 UTC, C10udburst commented
> wait dont push

bruhh u know that draft PRs exist right?

2022-11-28 15:25 UTC, ImZaw commented
> > wait dont push
> 
> bruhh u know that draft PRs exist right?

what is this

2022-11-28 15:29 UTC, C10udburst commented
draft prs prevents us from merging unless u undraft them

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

2022-11-28 15:36 UTC, ImZaw commented
> draft prs prevents us from merging unless u undraft them
> 
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

well i was gonna push a push rq and merge

2022-11-28 15:37 UTC, ImZaw commented
anywYs i think u can merge

2022-11-28 15:45 UTC, C10udburst approved these changes

2022-11-28 18:42 UTC, Blatzar requested changes

2022-11-28 18:42 UTC, Blatzar commented on NineGoalProvider/src/main/kotlin/com/ninegoal/9GoalProvider.kt
> +            val language = it.name?.replace(" (${it.name?.substringAfter("(")?.substringBefore(")")})", "") ?: ""
regex here please

2022-11-28 18:50 UTC, ImZaw commented on NineGoalProvider/src/main/kotlin/com/ninegoal/9GoalProvider.kt
> +            val language = it.name?.replace(" (${it.name?.substringAfter("(")?.substringBefore(")")})", "") ?: ""
“ \(.*“
should it be double \\ or im not sure cause im on phone

2022-11-28 18:51 UTC, ImZaw commented on NineGoalProvider/src/main/kotlin/com/ninegoal/9GoalProvider.kt
> +            val language = it.name?.replace(" (${it.name?.substringAfter("(")?.substringBefore(")")})", "") ?: ""
before the (

2022-11-29 19:48 UTC, Blatzar commented on NineGoalProvider/src/main/kotlin/com/ninegoal/9GoalProvider.kt
> +    return Regex("""^(?:https?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:\/\n\?\=]+)""").find(this)?.groupValues?.firstOrNull()
Whats happening here?

2022-11-29 19:55 UTC, merged