Added SkillShare.com
recloudstream/cloudstream-extensions-multilingual pull request #71
Opened 2022-12-23 23:36 UTC by contusionglory

2022-12-24 07:37 UTC, C10udburst requested changes

2022-12-24 07:37 UTC, C10udburst commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +            """{         "query": "query GetClassesByType(${'$'}filter: ClassFilters!, ${'$'}pageSize: Int, ${'$'}cursor: String, ${'$'}type: ClassListType!, ${'$'}sortAttribute: ClassListByTypeSortA
i'm pretty sure you can use `"\$"` instead of `"${'$'}"`

2022-12-24 07:37 UTC, C10udburst commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +            """{         "query": "query GetClassesByType(${'$'}filter: ClassFilters!, ${'$'}pageSize: Int, ${'$'}cursor: String, ${'$'}type: ClassListType!, ${'$'}sortAttribute: ClassListByTypeSortA
you can also remove entries you arent using from the query, like `studentCount` for example

2022-12-24 07:37 UTC, C10udburst commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +            cursor =
are you sure you don't need to use 2 different cursors for trending and popular?

2022-12-24 07:37 UTC, C10udburst commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +            """{         "query": "query GetClassesByType(${'$'}filter: ClassFilters!, ${'$'}pageSize: Int, ${'$'}cursor: String, ${'$'}type: ClassListType!, ${'$'}sortAttribute: ClassListByTypeSortA
also you probably should set the cursor to null if the page variable indicates that its the first page

2022-12-24 07:37 UTC, C10udburst commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +            """{"query":"fragment ClassFields on Class {\n  id\n\tsmallCoverUrl\n  largeCoverUrl\n  sku\n  title\n  url\n}\n\nquery GetClassesQuery(${"$"}query: String!, ${"$"}where: SearchFilters!,
have you made sure that if someone types `"` as their query it doesnt break the request?

2022-12-24 07:37 UTC, C10udburst commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +        val document = app.get(bypassApiUrl + "/${data.courseId}/0")
i assume it wasn't possible to avoid using the replit page?

2022-12-24 09:19 UTC, 821938089 requested changes

2022-12-24 10:09 UTC, contusionglory commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +        val document = app.get(bypassApiUrl + "/${data.courseId}/0")
It's the way to bypass it, if you have a better way let me know

2022-12-24 10:10 UTC, contusionglory commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +            """{"query":"fragment ClassFields on Class {\n  id\n\tsmallCoverUrl\n  largeCoverUrl\n  sku\n  title\n  url\n}\n\nquery GetClassesQuery(${"$"}query: String!, ${"$"}where: SearchFilters!,
It doesn't return result no error

2022-12-24 10:10 UTC, contusionglory commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +            cursor =
Fixed with new commit

2022-12-24 10:11 UTC, contusionglory commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +            """{         "query": "query GetClassesByType(${'$'}filter: ClassFilters!, ${'$'}pageSize: Int, ${'$'}cursor: String, ${'$'}type: ClassListType!, ${'$'}sortAttribute: ClassListByTypeSortA
Cursor can't be null it need to be a blank string ""

2022-12-24 10:36 UTC, C10udburst requested changes

2022-12-24 10:36 UTC, C10udburst commented on SkillShareProvider/build.gradle.kts
> +    language= "it"
why italian?

2022-12-24 10:45 UTC, C10udburst approved these changes

2022-12-24 16:28 UTC, Blatzar reviewed
Looks pretty good, although there's some things which are good to know

2022-12-24 16:28 UTC, Blatzar commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +        home.let {
Why the let?

2022-12-24 16:28 UTC, Blatzar commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +            """{"query":"fragment ClassFields on Class {\n  id\n\tsmallCoverUrl\n  largeCoverUrl\n  sku\n  title\n  url\n}\n\nquery GetClassesQuery(${"$"}query: String!, ${"$"}where: SearchFilters!,
It would be preferable if you made these multi-line in the future to make reading/writing easier but you can keep this

2022-12-24 16:28 UTC, Blatzar commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +        val home = parseJson<SearchApiData>(responseBody).data!!.search!!.edges.map {
If you just make it non-nullable here you might as well make it non-nullable in the type system to make it easier to understand

2022-12-24 16:28 UTC, Blatzar commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +        if (page == 1)
This will be overwritten below which might cause some confusion in the future

2022-12-24 17:15 UTC, contusionglory commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +        home.let {
To prevent the home to be null and program crash because it try to take the last element of something that dosen't exists

2022-12-24 17:49 UTC, Blatzar commented on SkillShareProvider/src/main/kotlin/com/lagradost/SkillShareProvider.kt
> +        home.let {
That does not work if you do let without a question mark
Also if you want null checks use an if statement

2022-12-24 18:10 UTC, merged

2023-01-16 02:51 UTC, muzamilrafiq798 commented
How to download